// types/supabase.ts
// This file is automatically generated by the Next.js compiler.

export type Database = {
  public: {
    Tables: {
      articles: {
        Row: {
          id: string
          name: string
          description?: string | null
          category_id?: string | null
          price: number
          mrp?: number | null
          product_photos: string[]
          hsn_code?: string | null
          gst_percentage?: number | null
          weight?: number | null
          unit_of_measurement?: string | null
          cost_price?: number | null
          created_at: string
          updated_at: string
        }
      }
      categories: {
        Row: {
          id: string
          name: string
          description?: string | null
          parent_id?: string | null
          image_url?: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
      }
      carts: {
        Row: {
          id: string
          user_id: string
          created_at: string
          updated_at: string
        }
      }
      cart_items: {
        Row: {
          id: string
          cart_id: string
          product_id: string
          quantity: number
          created_at: string
          updated_at: string
        }
      }
      goods_receipt_notes: {
        Row: {
          id: string
          po_id: string
          received_date?: string | null
          status: "Received" | "Rejected"
          created_at: string
          updated_at: string
        }
      }
      iorders: {
        Row: {
          id: string
          customer_name: string
          total_amount: number
          status: "Received" | "Processed" | "Dispatched" | "Delivered"
          created_at: string
          updated_at: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string | null
          title: string
          message: string
          type: "info" | "success" | "warning" | "error"
          is_read: boolean
          is_test?: boolean | null
          reference_id?: string | null
          reference_type?: string | null
          created_at: string
          updated_at: string
        }
      }
      orders: {
        Row: {
          id: string
          customer_id: string
          total_amount: number
          delivery_address: string
          status:
            | "pending"
            | "approved"
            | "preparing"
            | "ready"
            | "in_transit"
            | "delivered"
            | "rejected"
            | "cancelled"
            | "failed"
            | "processing"
          delivery_boy_id?: string | null
          created_at: string
          updated_at: string
          status_reason?: string | null
        }
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          product_id: string
          quantity: number
          unit_price: number
          created_at: string
          updated_at: string
        }
      }
      owner_bank_accounts: {
        Row: {
          id: string
          registration_id: string
          account_holder_name: string
          account_number: string
          bank_name: string
          branch_name?: string | null
          ifsc_code: string
          account_type?: string | null
          is_primary: boolean
          created_at: string
          updated_at: string
        }
      }
      owner_identifications: {
        Row: {
          id: string
          registration_id: string
          id_type: "aadhar" | "pan" | "voter_id" | "driving_license" | "passport" | "ration_card" | "other"
          id_number: string
          id_name: string
          id_image_url?: string | null
          issue_date?: string | null
          expiry_date?: string | null
          issuing_authority?: string | null
          issuing_country?: string | null
          is_verified: boolean
          verification_notes?: string | null
          created_at: string
          updated_at: string
        }
      }
      payments: {
        Row: {
          id: string
          order_id: string
          amount: number
          payment_method: "cash" | "card" | "upi" | "other"
          payment_status: "pending" | "completed" | "failed" | "refunded"
          transaction_id?: string | null
          payment_details?: string | null
          created_at: string
          updated_at: string
        }
      }
      product_images: {
        Row: {
          id: string
          product_id: string
          image_url: string
          is_primary: boolean
          created_at: string
          updated_at: string
        }
      }
      products: {
        Row: {
          id: string
          name: string
          description?: string | null
          price: number
          stock?: number | null
          category?: string | null
          category_id?: string | null
          image_url?: string | null
          brand?: string | null
          hsn_code?: string | null
          vendor_id: string
          approval_status: "pending" | "approved" | "rejected"
          submitted_at: string
          approved_at?: string | null
          rejection_reason?: string | null
          created_at: string
          updated_at: string
        }
      }
      profiles: {
        Row: {
          id: string
          role: "admin" | "vendor" | "customer" | "delivery"
          full_name: string
          phone?: string | null
          address?: string | null
          created_at: string
          updated_at: string
        }
      }
      purchase_orders: {
        Row: {
          id: string
          vendor_id: string
          payment_terms: "0-3 days" | "4-7 days" | "8-15 days" | "16-30 days" | "More than 30 days"
          rtv: "Yes" | "No"
          po_status: "Draft" | "Approved" | "Cancelled" | "Completed"
          inbound_status: "Created" | "Approved" | "Dispatched" | "Delivered" | "Completed" | "Cancelled"
          validity_date?: string | null
          created_at: string
          updated_at: string
        }
      }
      purchase_order_items: {
        Row: {
          id: string
          po_id: string
          article_id: string
          cost_price: number
          mrp: number
          gst_percentage: number
          ordered_quantity: number
          received_quantity: number
          created_at: string
          updated_at: string
        }
      }
      shop_owner_documents: {
        Row: {
          id: string
          registration_id: string
          document_type:
            | "identity_proof"
            | "address_proof"
            | "business_license"
            | "gst_certificate"
            | "shop_photo"
            | "other"
          document_url: string
          file_name: string
          file_size: number
          file_type: string
          uploaded_by: string
          created_at: string
          updated_at: string
        }
      }
      shop_owner_registrations: {
        Row: {
          id: string
          user_id: string
          merchant_segment:
            | "grocery"
            | "electronics"
            | "clothing"
            | "pharmacy"
            | "hardware"
            | "stationery"
            | "restaurant"
            | "services"
            | "other"
          merchant_sub_segment?: string | null
          shop_name: string
          shop_display_name?: string | null
          shop_phone: string
          shop_email?: string | null
          shop_website?: string | null
          shop_gstin?: string | null
          owner_name: string
          owner_phone?: string | null
          owner_email?: string | null
          pan_number?: string | null
          sales_officer_id?: string | null
          document_url?: string | null
          status: "pending" | "under_review" | "approved" | "rejected"
          submitted_at: string
          approved_at?: string | null
          approved_by?: string | null
          rejection_reason?: string | null
          created_at: string
          updated_at: string
        }
      }
      vendors: {
        Row: {
          id: string
          name: string
          address?: string | null
          contact_number?: string | null
          email?: string | null
          trade_license?: string | null
          gst_number?: string | null
          fssai_license?: string | null
          bank_account_number?: string | null
          bank_name?: string | null
          bank_ifsc?: string | null
          is_active: boolean
          vendor_type?: string | null
          gst_file_url?: string | null
          fssai_file_url?: string | null
          aadhar_file_url?: string | null
          pan_file_url?: string | null
          created_at: string
          updated_at: string
        }
      }
      user_addresses: {
        Row: {
          id: string
          user_id: string
          address_type: "home" | "work" | "other"
          is_default: boolean
          name: string
          address_line1: string
          address_line2?: string | null
          city: string
          state: string
          postal_code: string
          country: string
          phone?: string | null
          landmark?: string | null
          created_at: string
          updated_at: string
        }
      }
    }
    Views: {}
    Functions: {
      check_table_exists: {
        Args: { table_name: string }
        Returns: boolean
      }
      create_product_images_table: {
        Args: {}
        Returns: void
      }
      get_tables: {
        Args: {}
        Returns: string[]
      }
    }
    Enums: {}
    CompositeTypes: {}
  }
}
